curveball/urls.py
# flake8: noqa
from pageblocks.urls import urlpatterns

uelc/urls.py
import os.path

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth.views
from django.views.generic import TemplateView
from django.views.static import serve
import djangowind.views

from uelc.main import views
import uelc.main.helper_functions
from uelc.main.views import (
    UELCPageView, UELCEditView, FacilitatorView, UELCAdminView,
    UELCAdminCohortView, UELCAdminCreateHierarchyView,
    UELCAdminDeleteHierarchyView, UELCAdminUserView, UELCAdminCaseView,
    UELCAdminEditUserView, UELCAdminCreateUserView, UELCAdminEditUserPassView,
    UELCAdminEditCaseView, UELCAdminCreateCohortView, UELCAdminEditCohortView,
    UELCAdminDeleteCohortView, UELCAdminDeleteCaseView,
    UELCAdminCreateCaseView, UELCAdminDeleteUserView,
    AddCaseAnswerToQuestionView, EditCaseAnswerView, DeleteCaseAnswerView,
    SubmitSectionView, CloneHierarchyWithCasesView, ResetUserCaseProgress)


admin.autodiscover()

site_media_root = os.path.join(os.path.dirname(__file__), "../media")
redirect_after_logout = getattr(settings, 'LOGOUT_REDIRECT_URL', None)
auth_urls = url(r'^accounts/', include('django.contrib.auth.urls'))
logout_page = url(r'^accounts/logout/$', django.contrib.auth.views.logout,
                  {'next_page': redirect_after_logout})
if hasattr(settings, 'CAS_BASE'):
    auth_urls = url(r'^accounts/', include('djangowind.urls'))
    logout_page = url(r'^accounts/logout/$', djangowind.views.logout,
                      {'next_page': redirect_after_logout})
    admin_logout_page = url(r'^admin/logout/$', djangowind.views.logout,
                            {'next_page': redirect_after_logout})


urlpatterns = [
    logout_page,
    admin_logout_page,
    auth_urls,
    url(r'^registration/', include('registration.backends.default.urls')),
    url(r'^$', views.IndexView.as_view()),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uelcadmin/case/', UELCAdminCaseView.as_view()),
    url(r'^uelcadmin/createhierarchy/',
        UELCAdminCreateHierarchyView.as_view()),
    url(r'^uelcadmin/cohort/(?P<pk>\d+)/', UELCAdminEditCohortView.as_view(),
        name='uelcadmin-edit-cohort'),
    url(r'^uelcadmin/cohort/', UELCAdminCohortView.as_view(),
        name='uelcadmin-view-cohort'),
    url(r'^uelcadmin/user/(?P<pk>\d+)/', UELCAdminEditUserView.as_view(),
        name='uelcadmin-edit-user'),
    url(r'^uelcadmin/user/', UELCAdminUserView.as_view(),
        name='uelcadmin-user-view'),
    url(r'^uelcadmin/createcohort/', UELCAdminCreateCohortView.as_view()),
    url(r'^uelcadmin/createcase/', UELCAdminCreateCaseView.as_view()),
    url(r'^uelcadmin/deletehierarchy/',
        UELCAdminDeleteHierarchyView.as_view()),
    url(r'^uelcadmin/editcase/', UELCAdminEditCaseView.as_view()),
    url(r'^uelcadmin/deletecase/', UELCAdminDeleteCaseView.as_view()),
    url(r'^uelcadmin/deletecohort/', UELCAdminDeleteCohortView.as_view()),
    url(r'^uelcadmin/createuser/', UELCAdminCreateUserView.as_view()),
    url(r'^uelcadmin/edituserpass/(?P<pk>\d+)/$',
        UELCAdminEditUserPassView.as_view(), name='uelcadmin_edituserpass'),
    url(r'^uelcadmin/deleteuser/', UELCAdminDeleteUserView.as_view()),
    url(r'^uelcadmin/', UELCAdminView.as_view(), name='uelcadmin'),
    url(r'^edit_question/(?P<pk>\d+)/add_case_answer/$',
        AddCaseAnswerToQuestionView.as_view(), {},
        'add-case-answer-to-question'),
    url(r'^edit_question/(?P<pk>\d+)/delete_case_answer/$',
        DeleteCaseAnswerView.as_view(), {},
        'delete-case-answer'),
    url(r'^edit_case_answer/(?P<pk>\d+)/$', EditCaseAnswerView.as_view(), {},
        'edit-case-answer'),
    url(r'^_impersonate/', include('impersonate.urls')),
    url(r'^stats/$', TemplateView.as_view(template_name="stats.html")),
    url(r'smoketest/', include('smoketest.urls')),
    url(r'infranil/', include('infranil.urls')),
    url(r'^uploads/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^pagetree/clone_hierarchy/(?P<hierarchy_id>\d+)/$',
        CloneHierarchyWithCasesView.as_view(), name='clone-hierarchy'),
    url(r'^pagetree/', include('pagetree.urls')),
    url(r'^quizblock/', include('quizblock.urls')),
    url(r'^pages_save_edit/(?P<hierarchy_name>[-\w]+)/(?P<path>.*)$',
        uelc.main.helper_functions.pages_save_edit),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/edit/(?P<path>.*)$',
        UELCEditView.as_view()),
    url(r'^submit_section/', SubmitSectionView.as_view()),
    url(r'^reset/(?P<case_id>\d+)/$',
        ResetUserCaseProgress.as_view(), name='reset-user-case-progress'),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/instructor/(?P<path>.*)$',
        uelc.main.helper_functions.instructor_page),
    url(r'^facilitator/fresh_token/$', uelc.main.helper_functions.fresh_token),
    url(r'^group_user/fresh_token/(?P<section_id>\d+)/$',
        uelc.main.helper_functions.fresh_grp_token),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/facilitator/(?P<path>.*)$',
        FacilitatorView.as_view(), name='facilitator-view'),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/(?P<path>.*)$',
        UELCPageView.as_view()),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

uelc/main/forms.py
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from pagetree.forms import CloneHierarchyForm
from pagetree.models import Hierarchy
from uelc.main.models import UserProfile, Cohort


class CreateUserForm(UserCreationForm):
    user_profile = forms.ChoiceField(
        required=True,
        widget=forms.Select(
            attrs={'class': 'create-user-profile', 'required': True}),
        choices=UserProfile.PROFILE_CHOICES,
        initial='group_user')
    cohort = forms.ModelChoiceField(
        widget=forms.Select(
            attrs={'class': 'cohort-select'}),
        queryset=Cohort.objects.all().order_by('name'),)
    username = forms.CharField(
        widget=forms.widgets.Input(
            attrs={'class': 'add-user-username'}))
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'class': 'add-user-password1', 'type': 'password', }))
    password2 = forms.CharField(
        label="Password confirm",
        widget=forms.PasswordInput(
            attrs={'class': 'add-user-password2',
                   'type': 'password',
                   'data-match': "#id_password1"}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class CreateHierarchyForm(forms.Form):
    name = forms.CharField(
        required=True,
        widget=forms.widgets.Input(
            attrs={'class': 'add-hierarchy-name',
                   'required': True}))


class UELCCloneHierarchyForm(CloneHierarchyForm):
    def clean(self):
        cleaned_data = super(UELCCloneHierarchyForm, self).clean()
        base_url = cleaned_data.get('base_url')

        # Pagetree's clone() function expects a "base_url" parameter
        # to give to the new Hierarchy.  UELC's pagetree is set up to
        # require the base_url to be in the format: /pages/url/
        # I want to handle the case where the user doesn't put the
        # base_url in that format without changing the way pagetree
        # works.
        m = re.match(r'^\/pages\/(\S+)\/$', base_url)
        if m is None:
            # base_url isn't in the recognizable format, so assume it's
            # a slug.
            base_url = '/pages/%s/' % base_url
            if Hierarchy.objects.filter(base_url=base_url).exists():
                raise forms.ValidationError(
                    'There\'s already a hierarchy with ' +
                    'the base_url: {}'.format(base_url))
            cleaned_data['base_url'] = base_url

        return cleaned_data


class EditUserPassForm(forms.Form):
    newPassword1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'class': 'new-user-password1', 'type': 'password', }))
    newPassword2 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'class': 'new-user-password2', 'type': 'password', }))


class CaseAnswerForm(forms.Form):
    value = forms.IntegerField(required=True, min_value=1)
    title = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, required=True)

uelc/templates/pagetree/base_pagetree.html
{% extends 'base.html' %}

uelc/templates/pagetree/curveball.html
{% load get_selected_curveball %}
{% load bootstrap %}

<div class="gated-curveball panel panel-default">
    {% get_selected_curveball u.0 sec.7.1 as selected_curveball %}
    {% if selected_curveball %}
        <div class="panel-body">
			<label>Selected Curveball</label>
             <p>{{ selected_curveball.curveball.title }}</p>
        </div>
    {% else %}
        <div class="panel-body">
            <form name="curveball-form-select" id="curveball-form-{{ sec.7.1.id }}-user-{{ u.0.id }}" action="." method="post">{% csrf_token %}
                {{sec.7.1.curveball_select_form|bootstrap}}
                <input type="hidden" name="curveball-block-id" value="{{ sec.7.1.id }}" />
                <input type="hidden" name="user_id" value="{{u.0.id}}" />
                <input type="hidden" name="curveball-select" value="submit" />
                <button type="submit" class="pull-left btn btn-default curveball-commit-btn">Commit</button> 
            </form>
            <span class="clearfix"></span>
         </div>
    {% endif %}
</div>

uelc/templates/pagetree/facilitator.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load part_string %}

{% block title %} | Facilitation{% endblock %}

{% block js %}
    <script>
        window.hierarchy_name = '{{section.hierarchy.name}}';
        window.username = '{{request.user.username}}';
        window.freshTokenUrl = '/facilitator/fresh_token/';
        window.token = '{{token}}';
        window.websocketsBase = '{{websockets_base}}';
    </script>
    <script type="text/javascript" src="{{STATIC_URL}}js/uelc_admin/web_socks.js"></script>
    <script src="{{STATIC_URL}}js/uelc_admin/uelc_facilitator.js"></script>
{% endblock %}

{% block content %}

<div id="content" class="container-fluid">
    <h1>Case Control for {{case.name}}</h1>

    <div class="row">
        <div class="col-sm-9">
            <p>
            Use the case control panel below to track your assigned group user along the progress path of the case. The case control will provide you alerts on group user decisions and progress. The system will prompt you to take action when a group user is waiting for you to unlock new content.
            </p>
        </div>
        <div class="col-sm-3">
            <a href="https://docs.google.com/document/d/1pPH3pJBdGQ7JnnDd5vidBdfV0u35bTM3lnul9AsTOIE/edit?usp=sharing" class="btn btn-primary btn-sm" role="button" target="_blank"><span class="glyphicon glyphicon-new-window" aria-hidden="true"></span> Case Control Cheatsheet</a>
        </div>
    </div>

    {% for u in user_sections %}
        {% if u.0.profile.profile_type == "group_user" %}
            <div class="col-sm-3 text-center">
                <div class="gate-sections" id="group-user-section-{{u.0.id}}">
                    <div class="group-name panel panel-default"
                        {% if forloop.counter < 5 %}
                            data-spy="affix" data-offset-top="200"
                        {% endif %}
                    >
                        <div class="panel-body">
                            <h4 class="facilitator-usrnm">Group {{u.0}}</h4>
                            <button class="btn btn-xs btn-default pull-left reset-progress"
                                data-user-id="{{u.0.id}}" data-username="{{u.0}}">
                                reset
                            </button>
                            <div class="user-icon
                                <span class="glyphicon glyphicon-user pull-right" aria-hidden="true"></span>
                            </div>
                        </div>
                    </div>
                    <div class="gate-section-list well well-sm">
                        {% for sec in u.1 %}
                            {% if sec.2 %} <!-- if unlocked -->
                                {% if sec.5 %} <!-- can show gateblock -->
                                    <div class="group-btn-list gate-block part-{{sec.6.0|floatformat:'0'}}" data-section-id="{{sec.0.pk}}" data-user-loc="{{ u.2.id }}" data-group-id="{{u.0.id}}">
                                        {% if sec.7.0 %}<!-- if curveball -->
                                            {% include "pagetree/curveball.html" %}
                                        {% endif %}

                                        <div class="gate-section panel panel-default">
                                            <div class="panel-heading">
                                                <h3 class="panel-title text-center">{{ sec.1.pageblock.label }}</h3>
                                            </div>

                                            <div class="panel-body">
                                                <div class="pull-left badge text-capitalize status {{sec.4}}">{{sec.4}}</div>
                                                {% if sec.0.pk == u.2.id %}
                                                    <div class="pull-right user-icon">
                                                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                                    </div>
                                                {% endif %}
                                                {% if sec.8.0 and sec.8.2 %} <!-- if decision block and responded -->
                                                <div class="response">
                                                    <p>{{ sec.8.2.title }}</p>
                                                </div>
                                                {% endif %}
                                            </div>
                                        </div><!--end .gate-section-->

                                        <div class="gate-button unlocked {%if sec.9.0%}hidden{%endif%}" data-part-dec-raw="{{sec.6.1}}" data-part-decision="{{sec.6.1|convert_part2}}">
                                            <div class="btn-group-vertical" role="group" aria-label="..."  style="width: 100%;">
                                                <div type="submit" class="btn btn-sm btn-success text-center status-{{sec.4}}" style="margin-top: 5px;">
                                                    <span>{{ sec.1.pageblock.label }}</span><br/>
                                                    <span>Unlocked </span>
                                                    <span><span class="glyphicon glyphicon-ok" aria-hidden="true">
                                                </div>
                                            </div>
                                            <div class="separator">
                                                <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
                                            </div>
                                            <div class="clearfix visible-lg-block"></div>
                                        </div><!-- end .gate-button-->
                                    </div><!-- end .gate-block-->
                                {% endif %}
                            {% else %}<!-- gateblock is locked-->
                                {% if sec.5 %} <!-- can show gateblock -->
                                    <div class="group-btn-list gate-block part-{{sec.6.0|floatformat:'0'}} {% if sec.4 == 'reviewed' %}active{% endif%}" data-section-id="{{sec.0.pk}}" data-user-loc="{{ u.2.id }}" data-group-id="{{u.0.id}}">
                                        {% if sec.7.0 %} <!-- if curveball -->
                                            {% include "pagetree/curveball.html" %}
                                        {% endif %}

                                        <div class="gate-section panel panel-default">
                                            <div class="panel-heading">
                                                <h3 class="panel-title text-center">{{ sec.1.pageblock.label }}</h3>
                                            </div>

                                            <div class="panel-body">
                                                <div class="badge pull-left text-capitalize status {{sec.4}}">{{sec.4}}</div>
                                                {% if sec.0.pk == u.2.id %}
                                                    <div class="pull-right user-icon">
                                                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                                    </div>
                                                {% endif %}
                                                {% if sec.8.0 and sec.8.2 %} <!-- if decision block and responded -->
                                                    <div class="response">
                                                        <p>{{ sec.8.2.title }}</p>
                                                    </div>
                                                {% endif %}
                                            </div>
                                        </div><!--end .gate-section-->

                                        <div class="gate-button {%if sec.9.0%}hidden{%endif%} locked {{sec.6.0|convert}}" data-part-dec-raw="{{sec.6.1}}" data-part-decision="{{sec.6.1|convert_part2}}">
                                            <form action ="." method="post">{% csrf_token %}
                                                <div class="btn-group-vertical" role="group" aria-label="..."  style="width: 100%;">
                                                    <div display="none" type="none" class="btn btn-sm btn-danger btn-block text-center" style="margin-top: 5px;">
                                                        <span>{{ sec.1.pageblock.label }}</span><br/>
                                                        <span>Locked </span><span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                                                        <span>
                                                    </div>
                                                </div>
                                                <div class="clearfix visible-lg-block"></div>
                                                <input type="hidden" name="gate-action" value="submit" />
                                                <input type="hidden" name="user_type" value="{{u.0.profile.profile_type}}" />
                                                <input type="hidden" name="user_id" value="{{u.0.id}}" />
                                                <input type="hidden" name="section" value="{{sec.0.id}}" />
                                                <input type="hidden" name="block" value="{{sec.1.id}}" />
                                                <input type="hidden" class="post" value="{{sec.0.get_absolute_url}}">
                                            </form>
                                            <div class="separator">
                                                <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
                						    </div>
                                        </div><!-- end .gate-button-->
                                    </div><!-- end .gate-block -->
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div><!--end gaet-section-list-->
                </div><!--end gate-sections -->
            </div><!-- end .col-sm-3 -->
        {% endif %}
    {% endfor %}

    <br style="clear:both;"/>
</div><!--end .content -->


<div id="confirm-curveball-modal" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="Set Curveball" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                   Set Curveball
                </h4>
            </div>
            <div class="modal-body text-center">
                <h4 class="instructions"></h4>
                <div class="hidden loading-spinner"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary set-curveball">Yes. Set it.</button>
                <button type="button" class="btn btn-default cancel-curveball">Cancel</button> 
            </div>
        </div>
    </div>
</div>

<div id="confirm-reset-progress-modal" class="modal fade in" tabindex="-1"
    role="dialog" aria-labelledby="Reset Progress" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                   Confirm Reset
                </h4>
            </div>
            <div class="modal-body">
                <form method="post" action='{% url "reset-user-case-progress" case.id %}'>
                    {% csrf_token %}
                    <input type="hidden" name="user-id" value="" />
                    <p>Are you sure? This action will completely reset <b><span class="username"></span>'s</b> progress.</p>
                    <p><b>Important</b>: Before proceeding, direct the group user to exit the 
                    session by clicking the Eldex logo in the top left of their screen. Once the progress is cleared,
                    direct the user to reenter the session</p>
                    <div class="hidden loading-spinner"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger">Reset Progress</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

uelc/templates/pagetree/instructor_page.html
{% extends "pagetree/base_pagetree.html" %}

{% block title %}{{section.label}} (instructor){% endblock %}

{% block bodyclass %}instructor module-{{module.slug}}{% endblock %}

{% block bodyid %}section-{{section.id}}{% endblock %}

{% block sidenav %}
	<!-- ###### Secondary Navigation ###### -->
	<div id="secondary_navigation">
		<div id="fadetop"></div>
		<div class="block">
			<h3>Sections</h3>
{% with "/instructor" as menu_base %}
{% include "pagetree/menu.html" %}
{% endwith %}
		</div><!-- div id="block" -->
		<div id="fadebottom"></div>
	</div><!-- div id="secondary_navigation" -->
{% endblock %}

{% block moduletabs %}

<ul class="nav navbar-nav">
  {% for section in modules %}
  <li{% ifequal section.id module.id %} class="active"{% endifequal %}><a href="{{section.get_instructor_url}}">{{section.label}}</a></li>
  {% endfor %}
</ul>

{% endblock %}

{% block navrightextra %}
<li><a href="{{section.get_absolute_url}}" class="btn btn-success">view page</a></li>
{% endblock %}


{% block content %}
<a href="{{section.get_absolute_url}}">student view of page</a>
<h1>{{ section.label }}</h1>

{% if quizzes %}
{% for quiz in quizzes %}
<h3>quiz {{quiz.id}}</h3>

{% if quiz.submission_set.count %}
<table width="100%">
{% for submission in quiz.submission_set.all %}
<tr class="submissionheader">
<th>{{submission.user.first_name}} {{submission.user.last_name}} ({{submission.user.username}})</th>
<td>{{submission.submitted}}</td>
</tr>
{% for response in submission.response_set.all %}
<tr class="submissionresponse">
<td>Question {{response.question.ordinality}}: {{response.question.text}}</td>
<td class="{% if response.question.answerable %}{% if response.is_correct %}correct{% else %}incorrect{% endif %}{% endif %}">{{response.value}}</td>
</tr>
{% endfor %}
{% endfor %}
</table>
{% else %}
<p>no submissions</p>
{% endif %}

{% endfor %}
{% else %}
<p>no quizzes on this page</p>
{% endif %}

<br style="clear:both"/>
{% endblock %}

{% block content-nav %}

{% if section.get_previous %}
<a href="{{section.get_previous.get_instructor_url}}" id="previous">« {{section.get_previous.label}}</a>
{% endif %}

{% if section.get_next %}
<a href="/instructor{{section.get_next.get_instructor_url}}" id="next">{{section.get_next.label}} »</a>
{% endif %}

{% endblock %}

uelc/templates/pagetree/menu.html
{% if not request.user.profile.is_group_user %}
<ul class="side-nav well well-lg">
    {% for s in module.get_descendants %}
    {% ifequal s.id module.id %}
    {% else %}
    <li class="menu-{{s.depth}}">
    {% ifnotequal s.id section.id %}
    {% ifequal menu_base "/edit" %}
    <a href="{{s.get_edit_url}}">
    {% else %}
    {% ifequal menu_base "/instructor" %}
    <a href="{{s.get_instructor_url}}">
    {% else %}
    <a href="{{menu_base}}{{s.get_absolute_url}}">
    {% endifequal %}
    {% endifequal %}
    {% else %}
    {% endifnotequal %}
    {{s.label}}
    {% ifnotequal s.id section.id %}
    </a>
    {% else %}
    {% endifnotequal %}
    {% if s.get_children %}
    <ul id="section-ul-{{s.id}}">
    {% else %}
    {% if s.is_last_child %}
    {% for lc in s.closing_children %}
    </ul>
    {% endfor %}
    {% endif %}
    {% endif %}
    {% if s.get_children %}
    {% else %}
    </li>
    {% endif%}
    {% endifequal %}
    {% endfor %}
</ul>
{% else %}

    {% for part in module.get_root.get_children %}
        {% if forloop.counter == 1 %}
                <ul class="side-nav well well-lg group-user">
                    {% for s in module.get_children %}
                        {% if section in s.get_siblings %}
                            {% if module.id == part.id %}
                                {% ifequal s.id module.id %}
                                    {% else %}
                                    <li class="menu-{{s.depth}}">
                                        <a href="{{menu_base}}{{s.get_absolute_url}}">
                                            {{s.label}}
                                        </a>
                                    </li>
                                {% endifequal %}
                            {% endif %}
                        {% endif %}

                    {% endfor %}
                </ul>
        {% endif %}
    {% endfor %}
    <script>
        jQuery(document).ready(function(){
            var ul = jQuery('ul.group-user');
            var loc = window.location.href.split('://').pop();
            var menuLinks = jQuery('.side-nav').find('a');
            
            if(ul.children().length == 0){
                window.ul = ul;
                ul.parent().remove();
            }else{
                ul.parent().prev().removeClass('col-sm-12').addClass('col-sm-9');
            }
            menuLinks.each(function(){
                hosturl = window.location.host;
                fullUrl = hosturl + jQuery(this).attr('href');
                if(fullUrl == loc){
                    jQuery(this).addClass('active');
                }
            })


        })
    </script>
{% endif %}

uelc/templates/pagetree/toc.html
{% if section.get_children %}
{% if section.show_toc %}
<div class="table-of-contents">
<h3>Table of Contents</h3>

{% if section.deep_toc %}
<ul class="toc">
{% for s in section.get_descendants %}
<li class="menu-{{s.depth}}">
  <a href="{{s.get_absolute_url}}">{{s.label}}</a>
  {% if s.get_children %}
     <ul id="section-ul-{{s.id}}">
  {% else %}
     {% if s.is_last_child %}
       {% for lc in s.closing_children %}
         </ul>
       {% endfor %}
     {% endif %}
  {% endif %}

  {% if s.get_children %}
  {% else %}
    </li>
  {% endif %}
{% endfor %}
</ul>

{% else %}
<ul class="toc">
{% for child in section.get_children %}
   <li><a href="{{child.get_absolute_url}}">{{child.label}}</a></li>
{% endfor %}
</ul>
{% endif %}

</div>
{% endif %}
{% endif %}

uelc/templates/pagetree/uelc_admin_cohort_edit.html
{% extends 'pagetree/uelc_admin.html' %}
{% load bootstrap %}

{% block introduction %}
    <ol class="breadcrumb">
        <li><a href="{% url 'uelcadmin' %}">Management Panel</a></li>
        <li><a href="{% url 'uelcadmin-view-cohort' %}">Cohorts</a></li>
        <li class="active">Edit Cohort</li>
    </ol>
{% endblock %}

{% block cohort %}
    <div class="panel panel-default">
        <div class="panel-heading">Edit {{cohort.name}}</div>
            <div class="panel-body">
                <form data-toggle="validator" id="edit-cohort-form-{{cohort.id}}" action="." method="post">{% csrf_token %}
                    {{cohort.edit_form|bootstrap}}
                    <input type="hidden" name="cohort_id" value="{{cohort.id}}">
                    <input type="submit" class="btn btn-primary form-submit" value="Submit">
                    <input type="reset" class="reset-button hidden" value="Reset" />
                </form>
            </div>
        </div>
    </div>
{% endblock %}

uelc/templates/pagetree/uelc_admin_user_pass_reset.html
{% extends 'pagetree/uelc_admin.html' %}
{% load bootstrap %}

{% block js %}
    <script>
    jQuery(document).ready(function(){
      jQuery('label[for="id_newPassword1"]').text('New Password')
      jQuery('label[for="id_newPassword2"]').text('Confirm New Password')
    })
    </script>
{% endblock %}

{% block introduction %}
    <ol class="breadcrumb">
        <li><a href="{% url 'uelcadmin' %}">Management Panel</a></li>
        <li><a href="{% url 'uelcadmin-view-cohort' %}">Cohorts</a></li>
        <li><a href="{% url 'uelcadmin-edit-user' user.id %}">Edit {{user.username}}</a></li>
        <li class="active">Edit Password</li>
    </ol>
{% endblock %}

{% block edituserpass %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <p>Edit Password for: {{user.username}}
      </div>

      <div class="panel-body">
          <form role="form" data-toggle="validator" id="add-user-form" action="." method="post">{% csrf_token %}
              {{edit_user_pass_form|bootstrap}}
              <input type="submit" class="btn btn-primary form-submit" value="Submit">
              <input type="reset" class="reset-button hidden" value="Reset" />
          </form>
      </div>
  </div>
{% endblock %}