uelc/urls.py
import os.path

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth.views
from django.views.generic import TemplateView
from django.views.static import serve
import djangowind.views

from uelc.main import views
import uelc.main.helper_functions
from uelc.main.views import (
    UELCPageView, UELCEditView, FacilitatorView, UELCAdminView,
    UELCAdminCohortView, UELCAdminCreateHierarchyView,
    UELCAdminDeleteHierarchyView, UELCAdminUserView, UELCAdminCaseView,
    UELCAdminEditUserView, UELCAdminCreateUserView, UELCAdminEditUserPassView,
    UELCAdminEditCaseView, UELCAdminCreateCohortView, UELCAdminEditCohortView,
    UELCAdminDeleteCohortView, UELCAdminDeleteCaseView,
    UELCAdminCreateCaseView, UELCAdminDeleteUserView,
    AddCaseAnswerToQuestionView, EditCaseAnswerView, DeleteCaseAnswerView,
    SubmitSectionView, CloneHierarchyWithCasesView, ResetUserCaseProgress)


admin.autodiscover()

site_media_root = os.path.join(os.path.dirname(__file__), "../media")
redirect_after_logout = getattr(settings, 'LOGOUT_REDIRECT_URL', None)
auth_urls = url(r'^accounts/', include('django.contrib.auth.urls'))
logout_page = url(r'^accounts/logout/$', django.contrib.auth.views.logout,
                  {'next_page': redirect_after_logout})
if hasattr(settings, 'CAS_BASE'):
    auth_urls = url(r'^accounts/', include('djangowind.urls'))
    logout_page = url(r'^accounts/logout/$', djangowind.views.logout,
                      {'next_page': redirect_after_logout})
    admin_logout_page = url(r'^admin/logout/$', djangowind.views.logout,
                            {'next_page': redirect_after_logout})


urlpatterns = [
    logout_page,
    admin_logout_page,
    auth_urls,
    url(r'^registration/', include('registration.backends.default.urls')),
    url(r'^$', views.IndexView.as_view()),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uelcadmin/case/', UELCAdminCaseView.as_view()),
    url(r'^uelcadmin/createhierarchy/',
        UELCAdminCreateHierarchyView.as_view()),
    url(r'^uelcadmin/cohort/(?P<pk>\d+)/', UELCAdminEditCohortView.as_view(),
        name='uelcadmin-edit-cohort'),
    url(r'^uelcadmin/cohort/', UELCAdminCohortView.as_view(),
        name='uelcadmin-view-cohort'),
    url(r'^uelcadmin/user/(?P<pk>\d+)/', UELCAdminEditUserView.as_view(),
        name='uelcadmin-edit-user'),
    url(r'^uelcadmin/user/', UELCAdminUserView.as_view(),
        name='uelcadmin-user-view'),
    url(r'^uelcadmin/createcohort/', UELCAdminCreateCohortView.as_view()),
    url(r'^uelcadmin/createcase/', UELCAdminCreateCaseView.as_view()),
    url(r'^uelcadmin/deletehierarchy/',
        UELCAdminDeleteHierarchyView.as_view()),
    url(r'^uelcadmin/editcase/', UELCAdminEditCaseView.as_view()),
    url(r'^uelcadmin/deletecase/', UELCAdminDeleteCaseView.as_view()),
    url(r'^uelcadmin/deletecohort/', UELCAdminDeleteCohortView.as_view()),
    url(r'^uelcadmin/createuser/', UELCAdminCreateUserView.as_view()),
    url(r'^uelcadmin/edituserpass/(?P<pk>\d+)/$',
        UELCAdminEditUserPassView.as_view(), name='uelcadmin_edituserpass'),
    url(r'^uelcadmin/deleteuser/', UELCAdminDeleteUserView.as_view()),
    url(r'^uelcadmin/', UELCAdminView.as_view(), name='uelcadmin'),
    url(r'^edit_question/(?P<pk>\d+)/add_case_answer/$',
        AddCaseAnswerToQuestionView.as_view(), {},
        'add-case-answer-to-question'),
    url(r'^edit_question/(?P<pk>\d+)/delete_case_answer/$',
        DeleteCaseAnswerView.as_view(), {},
        'delete-case-answer'),
    url(r'^edit_case_answer/(?P<pk>\d+)/$', EditCaseAnswerView.as_view(), {},
        'edit-case-answer'),
    url(r'^_impersonate/', include('impersonate.urls')),
    url(r'^stats/$', TemplateView.as_view(template_name="stats.html")),
    url(r'smoketest/', include('smoketest.urls')),
    url(r'infranil/', include('infranil.urls')),
    url(r'^uploads/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^pagetree/clone_hierarchy/(?P<hierarchy_id>\d+)/$',
        CloneHierarchyWithCasesView.as_view(), name='clone-hierarchy'),
    url(r'^pagetree/', include('pagetree.urls')),
    url(r'^quizblock/', include('quizblock.urls')),
    url(r'^pages_save_edit/(?P<hierarchy_name>[-\w]+)/(?P<path>.*)$',
        uelc.main.helper_functions.pages_save_edit),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/edit/(?P<path>.*)$',
        UELCEditView.as_view()),
    url(r'^submit_section/', SubmitSectionView.as_view()),
    url(r'^reset/(?P<case_id>\d+)/$',
        ResetUserCaseProgress.as_view(), name='reset-user-case-progress'),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/instructor/(?P<path>.*)$',
        uelc.main.helper_functions.instructor_page),
    url(r'^facilitator/fresh_token/$', uelc.main.helper_functions.fresh_token),
    url(r'^group_user/fresh_token/(?P<section_id>\d+)/$',
        uelc.main.helper_functions.fresh_grp_token),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/facilitator/(?P<path>.*)$',
        FacilitatorView.as_view(), name='facilitator-view'),
    url(r'^pages/(?P<hierarchy_name>[-\w]+)/(?P<path>.*)$',
        UELCPageView.as_view()),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

curveball/models.py
from random import randint

from ckeditor.widgets import CKEditorWidget
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from pagetree.generic.models import BasePageBlock
from pagetree.models import UserLocation


class Curveball(models.Model):
    title = models.TextField(blank=True)
    explanation = models.TextField(max_length=255, null=True, blank=True)
    ''' create a flag to know whether the curveball has been selected
    by the facilitator to appear for the group or not '''

    def __unicode__(self):
        return unicode(self.title)

    def as_dict(self):
        return {
            'title': self.title,
            'explanation': self.explanation,
        }

    @classmethod
    def create_from_dict(cls, d):
        if type(d) is not dict:
            d = d.as_dict()
        return cls.objects.create(**d)


class CurveballBlock(BasePageBlock):
    template_file = "curveball/curveballblock.html"
    display_name = "Curveball Block"
    description = models.TextField(blank=True)
    curveball_one = models.ForeignKey(Curveball, null=True, blank=True,
                                      related_name='curveball_one')
    curveball_two = models.ForeignKey(Curveball, null=True, blank=True,
                                      related_name='curveball_two')
    curveball_three = models.ForeignKey(Curveball, null=True, blank=True,
                                        related_name='curveball_three')

    def as_dict(self):
        d = super(CurveballBlock, self).as_dict()
        d.update({
            'description': self.description,
            'curveball_one': self.curveball_one.as_dict(),
            'curveball_two': self.curveball_two.as_dict(),
            'curveball_three': self.curveball_three.as_dict(),
        })
        return d

    @classmethod
    def create_from_dict(cls, d):
        d['curveball_one'] = Curveball.create_from_dict(
            d['curveball_one'])
        d['curveball_two'] = Curveball.create_from_dict(
            d['curveball_two'])
        d['curveball_three'] = Curveball.create_from_dict(
            d['curveball_three'])
        return cls.objects.create(**d)

    def _get_section(self):
        return self.pageblock().section

    section = property(_get_section)

    def get_curveballs(self):
        return [self.curveball_one, self.curveball_two, self.curveball_three]

    def get_latest_curveball_submission(self, group_user):
        selected_curveballs = []
        cbs = self.get_curveballs()

        for cb in cbs:
            try:
                cb_sub = cb.curveballsubmission_set.filter(
                    group_curveball=group_user).latest('submitted')
                if cb_sub:
                    selected_curveballs.append(cb_sub)
            except ObjectDoesNotExist:
                pass
        selected_curveballs.sort(key=lambda x: x.submitted)
        if selected_curveballs:
            latest_curveball_submission = selected_curveballs.pop()
            return latest_curveball_submission

        return None

    def redirect_to_self_on_submit(self):
        return False

    def clear_user_submissions(self, user):
        CurveballSubmission.objects.filter(
            curveballblock_id=self.id,
            curveballblock_user_id=user.id).delete()

    def needs_submit(self):
        return True

    def allow_redo(self):
        return False

    def unlocked(self, user, section):
        return CurveballSubmission.objects.filter(
            curveballblock_id=self.id,
            curveballblock_user_id=user.id).count() > 0

    def status(self, user, hierarchy):
        curveball_section = self.pageblock().section
        h_url = hierarchy.get_absolute_url()
        cb_url = curveball_section.get_absolute_url()
        status = 'None'
        unlocked = self.unlocked(user, curveball_section)
        if unlocked:
            status = 'completed'
        try:
            uloc = UserLocation.objects.get_or_create(
                user=user,
                hierarchy=hierarchy)
            uloc_path = h_url + uloc[0].path
            page_status = self.pageblock().section.get_uservisit(user).status
            if uloc_path == cb_url:
                status = "waiting"
                return status
            if not unlocked and page_status == "incomplete":
                status = "in progress"
                return status
        except (UserLocation.MultipleObjectsReturned, ValueError):
            status = "incomplete"
        return status

    @staticmethod
    def add_form():
        class AddForm(forms.Form):
            EDITOR = 'editor-{}'.format(randint(0, 5000))  # nosec
            choice_one_title = forms.CharField(label="Choice One Label")
            choice_one_explanation = forms.CharField(
                label="Choice One Content", widget=CKEditorWidget(
                    attrs={"id": EDITOR + 'add-choice-1'}))
            choice_two_title = forms.CharField(label="Choice Two Label")
            choice_two_explanation = forms.CharField(
                label="Choice Two Content", widget=CKEditorWidget(
                    attrs={"id": EDITOR + 'add-choice-2'}))
            choice_three_title = forms.CharField(label="Choice Three Label")
            choice_three_explanation = forms.CharField(
                label="Choice Three Content", widget=CKEditorWidget(
                    attrs={"id": EDITOR + 'add-choice-3'}))
        return AddForm()

    @staticmethod
    def create(request):
        return CurveballBlock.objects.create(
            curveball_one=Curveball.objects.create(
                title=request.POST.get('choice_one_title', ''),
                explanation=request.POST.get('choice_one_explanation', '')
            ),
            curveball_two=Curveball.objects.create(
                title=request.POST.get('choice_two_title', ''),
                explanation=request.POST.get('choice_two_explanation', '')
            ),
            curveball_three=Curveball.objects.create(
                title=request.POST.get('choice_three_title', ''),
                explanation=request.POST.get('choice_three_explanation', '')
            )
            )

    def edit_form(self):
        class EditForm(forms.Form):
            EDITOR = "editor-" + str(self.id)
            choice_one_title = forms.CharField(
                label="Choice One Label", initial=self.curveball_one.title)
            choice_one_explanation = forms.CharField(
                label="Choice One Content",
                initial=self.curveball_one.explanation,
                widget=CKEditorWidget(attrs={"id": EDITOR + 'choice-one'}))
            choice_two_title = forms.CharField(
                label="Choice Two Label", initial=self.curveball_two.title)
            choice_two_explanation = forms.CharField(
                label="Choice Two Content",
                initial=self.curveball_two.explanation,
                widget=CKEditorWidget(attrs={"id": EDITOR + 'choice-two'}))
            choice_three_title = forms.CharField(
                label="Choice Three Label", initial=self.curveball_three.title)
            choice_three_explanation = forms.CharField(
                label="Choice Three Content",
                initial=self.curveball_three.explanation,
                widget=CKEditorWidget(attrs={"id": EDITOR + 'choice-three'}))
        return EditForm()

    ''' a form so the facilitator can choose which curball to throw to
    the group user '''
    def curveball_select_form(self):
        class CurveballSelectForm(forms.Form):
            CURVEBALL_CHOICES = (
                (self.curveball_one.id, self.curveball_one),
                (self.curveball_two.id, self.curveball_two),
                (self.curveball_three.id, self.curveball_three),
            )
            curveball = forms.ChoiceField(
                required=True,
                label='Assign Curveball',
                widget=forms.Select(
                    attrs={'class': 'curveball-select', 'required': True}),
                choices=CURVEBALL_CHOICES,
                initial='1')

        return CurveballSelectForm()

    def edit(self, vals, files):
        self.curveball_one.title = vals.get('choice_one_title', '')
        self.curveball_one.explanation = vals.get(
            'choice_one_explanation', '')
        self.curveball_one.save()
        self.curveball_two.title = vals.get('choice_two_title', '')
        self.curveball_two.explanation = vals.get(
            'choice_two_explanation', '')
        self.curveball_two.save()
        self.curveball_three.title = vals.get('choice_three_title', '')
        self.curveball_three.explanation = vals.get(
            'choice_three_explanation', '')
        self.curveball_three.save()
        self.save()

    def create_submission(self, group_user, curveball):
        CurveballSubmission.objects.create(
            curveball=curveball,
            curveballblock=self,
            group_curveball=group_user)


class CurveballSubmission(models.Model):
    curveball = models.ForeignKey(Curveball, null=True, blank=True)
    curveballblock = models.ForeignKey(CurveballBlock)
    '''associate the group with the curveball so we know
    what group this curveball belongs to'''
    group_curveball = models.ForeignKey(User, related_name='curveball_user')
    '''group user has been shown curveball and has read it'''
    group_confirmation = models.BooleanField(default=False)
    submitted = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "curveball %d submission by %s at %s for choice %s" % (
            self.curveballblock.id, unicode(self.group_curveball),
            self.submitted, unicode(self.curveball))

uelc/templates/quizblock/answer_confirm_delete.html
<html>
	<body>
		<form action="." method="post">
			{% csrf_token %}
			Are you Sure?
      <input type="submit" value="Yes, delete it" />
	</form>
	</body>
</html>

uelc/templates/quizblock/edit_answer.html
{% extends "base.html" %}
{% load bootstrap %}
{% load accessible %}

{% block content %}

<ul class="breadcrumb">
    <li>
      {% get_quizblock_attr case_answer.answer.question.quiz.id as quizblock %}
      <a href="{{quizblock.edit_url}}">Back to Page Edit</a>
    </li>
    <li>
      <a href="{% url 'edit-quiz' case_answer.answer.question.quiz.id %}">
        Edit Decision
      </a>
    </li>
    <li>
        <a href="{% url 'add-case-answer-to-question' case_answer.answer.question.id %}">Edit Choices
            <!--{{case_answer.answer.question.display_number}}: {{ case_answer.answer.question.text }}-->
        </a>
    </li>
</ul>


<h2>Edit Decision choice</h2>
<p> <b>Choice Title:</b> {{case_answer.title}} </p>
<b>Choice Description:</b> <br /> 
<p> {{ case_answer.description }} </p>

<form action="." method="post" class="well form-horizontal" >{% csrf_token %}
  <table width="100%">
    {{ case_answer_form|bootstrap}}
  </table>
  <input type="submit" value="save" class="btn btn-primary" />
</form>

{% endblock %}

uelc/templates/quizblock/long_answer_show_answer.html
{% load markup %}
  {% comment %} short/long text questions {% endcomment %}
  {% if question.explanation %}
      <div class="casesanswerdisplay">
        <a href="#q{{question.id}}" class="moretoggle">Show explanation &gt;&gt;</a>
        <div id="q{{question.id}}" class="toggleable">
          <p>{{question.explanation|markdown}}</p>
        </div>
      </div>
  {% endif %}

uelc/templates/quizblock/long_text.html
{% load markup %}

{% if block.rhetorical %}
  <textarea rows="10" name="question{{question.id}}" class="form-control"></textarea>
{% else %}
  {% if response %}
    {% if block.allow_redo %}
    <textarea rows="10" name="pageblock-{{block.pageblock.id}}-question{{question.id}}" class="form-control">{{response.value}}</textarea>
    {% else %}
    <p class="yours">{{response.value|markdown}}</p>
    {% endif %}
  {% else %}
    <textarea rows="10" name="pageblock-{{block.pageblock.id}}-question{{question.id}}" class="form-control"></textarea>
  {% endif %}
{% endif %}

uelc/templates/quizblock/multiple_choice.html
{% load markup %}
{% load getresponse %}


<ol type="A">
  {% for answer in question.answer_set.all %}
    {% if block.rhetorical %}
      <li><input name="question{{question.id}}" value="{{answer.label}}" type="checkbox" />{{answer.label}}</li>
    {% else %}
      <li>
        {% if response %}
          {% comment %}
	  multi select is trickier. since there can be more than one correct
          response and more than one response by the user.
          {% endcomment %}
          {% ifanswerin response answer  %}
            <span class="text-primary  {% if answer.correct %}correct correctanswer{% else %}incorrect incorrectanswer{% endif %}">{{answer.label}}</span>
          {% else %}
            <span class="{% if answer.correct %}correct{% else %}incorrect{% endif %}">{{answer.label}}</span>
          {% endifanswerin %}
        {% else %}
          {% comment %}no response{% endcomment %}
          <input name="pageblock-{{block.pageblock.id}}-question{{question.id}}" value="{{answer.value}}" type="checkbox" />{{answer.label}}
        {% endif %}
      </li>
    {% endif %}
  {% endfor %}
</ol>

uelc/templates/quizblock/multiple_choice_show_answer.html
{% load markup %}
{% if block.rhetorical %}
      <div class="casesanswerdisplay">
        <a href="#q{{question.id}}" class="moretoggle">Show answer(s) &gt;&gt;</a>
        <div id="q{{question.id}}" class="toggleable">
          <p><i>The correct answer(s):</i></p>
	  <ol type="A">
	    {% for answer in question.answer_set.all %}
	      <li>
                {% if answer.correct %}
	          <span class="correctanswer">
		{% else %}
		  <span class="incorrectanswer" %>
		{% endif %}
		<span class="answer-inner">{{answer.label}}</span>
                </span>
              </li>
	    {% endfor %}
	  </ol>
          <p>{{question.explanation|markdown}}</p>
        </div>
      </div>
{% else %}
  <p>{{question.explanation|markdown}}</p>
{% endif %}

uelc/templates/quizblock/question.html
{% load markup %}
{% load getresponse %}
{% load bootstrap %}
{% getquestionresponse question as response %}
<div class="cases">
  <div class="question-intro-text">
  {{question.intro_text|markdown}}
  </div>
  <div class="casecontent">
    <div class="casequestion">
      <div class="question-text">
        {% if not request.user.profile.is_group_user %}
          <p><a data-toggle="modal" href="#edit-question-{{question.id}}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></p>
        {% endif  %}
      {{question.text|markdown}}
    </div>
      {% if question.answerable %}
        {% if block.rhetorical %}<form id="form-{{question.id}}" method="post">{% csrf_token %}{% endif %}

  {% if question.is_single_choice %}
      {% include 'quizblock/single_choice.html' %}
      {% if not request.user.profile.is_group_user %}
      <style>
        label[for="id_question_type"], label[for="id_intro_text"], label[for="id_explanation"], label[for="id_css_extra"]{
          display: none;
        }
        #id_question_type, #id_intro_text, #id_explanation, #id_css_extra{
          display: none;
        }
        #id_css_extra + p{
          display: none;
        }
      </style>
      


      <div id="edit-question-{{question.id}}" class="modal fade">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Edit Prompt</h4>
            </div>
            <div class="modal-body">

              <form data-post-url="{% url 'edit-question' question.id %}" action="." method="post" class="well form-horizontal" >{% csrf_token %}
                <table width="100%">
                {{ question.edit_form|bootstrap }}
                </table>
                <input type="button" value="save" class="btn btn-primary post-question" />
              </form>

            </div>
            <div class="modal-footer">
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

        <script>
          jQuery(document).ready(function(){
            jQuery('.post-question').click(function(){
              var postUrl = jQuery(this).parent().data('post-url');
              var formData = jQuery(this).parent().serialize();
              jQuery.post(postUrl, formData).success(function(){
                window.location.reload();
              }).error(function(){
                alert('Sorry, there was an error. Please submit changes again.')
              })

            })
          })
        </script>
      {% endif %}
  {% endif %}

  {% if question.is_single_choice_dropdown %}
      {% include 'quizblock/single_choice_dropdown.html' %}
  {% endif %}

  {% if question.is_multiple_choice %}
    {% include 'quizblock/multiple_choice.html' %}
  {% endif %}

        {% if block.rhetorical %}
          </form>
        {% endif %}
      {% else %}
        {% if question.is_short_text %}
          {% include 'quizblock/short_text.html' %}
        {% endif %}

        {% if question.is_long_text %}
          {% include 'quizblock/long_text.html' %}
        {% endif %}
      {% endif %}
    </div>

    {% if block.rhetorical %}
      {% include 'quizblock/show_answer.html' %}
    {% else %}
      {% if response %}
        {% include 'quizblock/show_answer.html' %}
      {% endif %}
  {% endif %}
  </div>
</div>

uelc/templates/quizblock/quiz_detail.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static from staticfiles %}
{% load accessible %}

{% block css %}
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">

    <style type="text/css">
        .draghandle {float: left;}
        #questions {list-style-type: none; margin: 0; padding: 0;}
        #questions li { margin: 0 3px 3px 3px; padding: 0.4em;
        padding-left: 1.5em; 
              background-color: #ddd;
        }
        #questions li span { position: absolute; margin-left: -1.3em; }
        .dragging {border: #f60 solid 1px;}
    </style>
{% endblock %}

{% block js %}
    {% include "quizblock/include_jquery.html" %}
    <script src="{% static 'quizblock/js/quizblock-admin.js' %}"></script>
    <script>
        (function($) {
        var url = "{% url 'reorder-questions' quiz.id %}";
        $(document).ready(function() {
            $("#questions").sortable({
                containment : 'parent',
                axis : 'y',
                tolerance: 'pointer',
                activeClass: 'dragging',
                handle: '.draghandle',
                stop: function(event, ui) {
                    quizblock.saveOrder($('#questions li'), url, 'question_');
                }
            });
            $("#questions").disableSelection();
        });
        })(quizblock.$);
    </script>
{% endblock %}

{% block content %}
{% get_quizblock_attr quiz.id as quizblock %}
<ul class="breadcrumb">
	<li><a href="{{quizblock.edit_url}}"><!--{{quizblock.label}}-->Back to Page Edit</a>
		
	</li>
	<li>Edit Decision</li>
</ul>


<h2>Edit Decision</h2>

{% if quiz.question_set.all.count == 0 %}
<form action="add_question/" method="post" class="well form-horizontal">{% csrf_token %}
<h2>Add Decision</h2>
<table width="100%">
{{quiz.add_question_form|bootstrap}}
</table>
<input type="submit" value="add decision" class="btn btn-primary" />
</form>
<script>
jQuery(document).ready(function(){
  var questionType = jQuery('#id_question_type').parent().parent();
  var introText = jQuery('#id_intro_text').parent().parent();
  var explanation = jQuery('#id_explanation').parent().parent()
  // select only Multiple choice: Single Answer
  jQuery('#id_question_type>option:eq(2)').prop('selected', true);
  questionType.hide();
  introText.hide();
  explanation.hide();
});
</script>
{% else %}
  {% for question in quiz.question_set.all %}

 
  <div class="question-text">
    
      <a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#edit-decision-{{question.id}}">
        <span class="glyphicon glyphicon-edit"></span>edit
      </a>
      {{question.text}}
  </div>
  <div id="edit-decision-{{question.id}}" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        Edit Decision
      </div>
      <div class="modal-body">
        
        <form data-post-url="{% url 'edit-question' question.id %}" action="." method="post" class="well form-horizontal">
          {% csrf_token %}
          <style>
          label[for=id_text] {
            visibility: hidden;
          }
          label[for=id_text]::before{
            content: "Prompt";
            visibility: visible;
          }
          </style>
          {{ question.edit_form|bootstrap }}
          <input id="submit-edit-decision" type="button" value="save" class="btn btn-primary" />
        </form>
        <div class="edit-choices"><a href="{% url 'add-case-answer-to-question' question.id %}"><button class="btn btn-primary btn-sm">Add or Edit Choices for this Decision</button></a>
        </div>

      </div>
      <div class="modal-footer"></div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
   
  <div class="delete-decision">
    <a href="{% url 'delete-question' question.id %}"><button class="btn btn-danger btn-sm">Delete Decision</button></a>
  </div>
  {% endfor %}
<script>
jQuery(document).ready(function(){
  var questionType = jQuery('#id_question_type').parent().parent();
  var introText = jQuery('#id_intro_text').parent().parent();
  var explanation = jQuery('#id_explanation').parent().parent()
  // select only Multiple choice: Single Answer
  jQuery('#id_question_type>option:eq(2)').prop('selected', true);
  questionType.hide();
  introText.hide();
  explanation.hide();
  jQuery('#submit-edit-decision').click(function(){
    var form = jQuery(this).parent();
    var formData = form.serialize();
    var postUrl = form.data('post-url');
    jQuery.post(postUrl, formData ).complete(function(){
      window.location.reload();
    }).error(function(){
      alert('Sorry, there was an error. Please submit again.');
    });
  });

})
</script>
{% endif %}


{% endblock %}

{% block primarynavrightextra %}
    <li><a href="{{section.get_absolute_url}}">View</a></li>
{% endblock %}

uelc/templates/quizblock/quizblock.html
{% load markup %}
{% load getresponse %}
{{ block.description|markdown }}

{% if request.user.is_anonymous %}
  <p class="warning">You must be logged in to view this content</p>
{% else %}

{% for question in block.question_set.all %}
  {% include 'quizblock/question.html' %}
{% endfor %}

{% if block.rhetorical %}
  <script src="http://mt.ccnmtl.columbia.edu/pedialabs/js/quizshow.js" type="text/javascript" language="javascript"></script>
{% endif %}	


{% endif %}

uelc/templates/quizblock/short_text.html
{% load markup %}

{% if block.rhetorical %}
  <input type="text" name="question{{question.id}}" class="form-control"/>
{% else %}
  {% if response %}
    <p class="text-primary ">{{response.value|markdown}}</p>
  {% else %}
    <input type="text" name="pageblock-{{block.pageblock.id}}-question{{question.id}}" class="form-control" />
  {% endif %}
{% endif %}
  